service: aws-node-projects
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

  vpc:
   

   subnets ID:
   - snkjdnkjnrxj
   - mvjknxjkfcnkjx



functions:
  function1:
    handler: index.sathish